In [1]:
import pandas as pd

In [6]:
pd.read_csv("../../results/jacint_results/reg_rnaseq/orthofinder_ogs_deseq/DESeq2_T0_AS_vs_S_MergedOGs.csv")

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,pvalue,padj
0,HVAEP6.G011316,1551.088384,0.270982,0.139795,0.052571,0.236708
1,HVAEP6.G011316,1551.088384,0.270982,0.139795,0.052571,0.236708
2,HVAEP6.G011470,306.830383,0.326936,0.189953,0.085225,0.321666
3,HVAEP6.G011470,306.830383,0.326936,0.189953,0.085225,0.321666
4,HVAEP6.G011470,306.830383,0.326936,0.189953,0.085225,0.321666
...,...,...,...,...,...,...
96755,HVAEP1.G002153,492.615762,0.983745,0.379239,0.009487,0.070235
96756,HVAEP1.G002176,492.615762,0.983745,0.379239,0.009487,0.070235
96757,HVAEP1.G002177,492.615762,0.983745,0.379239,0.009487,0.070235
96758,HVAEP1.G002178,492.615762,0.983745,0.379239,0.009487,0.070235
96759,HVAEP1.G002179,492.615762,0.983745,0.379239,0.009487,0.070235

In [7]:
pd.read_table("../../results/deseq2_rsem_final/hydra_all_deseq2_lg2.tsv")

,ID,EcoKD1_Eco1KD_B8_vs_control_B8,HydraAHL_3OC12_vs_control,HydraAHL_3OHC12_vs_control,HydraRecolonization_Conventionalized_vs_GF,HydraRecolonization_Conventionalized_vs_Wild,HydraRecolonization_Cvbct_vs_GF,HydraRecolonization_Cvbct_vs_Wild,HydraRecolonization_GF_vs_Wild,HydraRecolonization_Wild_vs_GF,HydraTemperature_08°C_vs_18°C,HydraTemperature_12°C_vs_18°C,HydraTemperature_22°C_vs_18°C
0,HVAEP6.G011796,-8.360376,0.726897,0.932251,1.829254,-0.268646,1.963838,-0.134062,-2.097900,2.097900,5.353596,5.139011,-1.165730
1,HVAEP2.G004481,-2.924442,0.008712,0.033244,0.189817,-0.015215,0.011431,-0.193601,-0.205032,0.205032,-0.139174,0.052093,-0.252938
2,HVAEP1.G000426,3.236053,-0.683156,-0.433207,0.054112,0.049654,0.112161,0.107703,-0.004458,0.004458,-0.333309,-0.128785,0.243423
3,HVAEP2.G004333,-2.766741,0.190227,0.047523,-0.963253,-0.053246,-0.593707,0.316300,0.910007,-0.910007,0.714210,0.464617,-0.221023
4,HVAEP1.G000462,3.253983,0.650198,0.219739,1.832917,0.205899,0.701865,-0.925152,-1.627018,1.627018,0.542742,0.570896,-0.971002
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19424,HVAEP4.G007784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000602,0.123693,-1.837544
19425,HVAEP10.G018079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.150833,-4.915957,0.956597
19426,HVAEP13.G024559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.926915,-6.286758,0.671275
19427,HVAEP3.G005290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.716380,-5.484606,1.587873
19428,HVAEP5.G010066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.999699,-4.454376,1.191050