In [8]:
import pandas as pd

In [9]:
popfile = "../data/goatools_data/population.txt"
population_genes = []
with open(popfile,"r") as pfile:
    for line in pfile.readlines():
        population_genes.append(line.rstrip())

In [10]:
df = pd.read_csv("../results/deseq2_rsem_sortmerna/tables/EcoKD1_Eco1KD_B8_vs_control_B8_results.csv")
df["gene"] = df["Unnamed: 0"].apply(lambda x: x.split(".")[1])
df.head()

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,gene
0,HVAEP6.G011796,12798.527212,-8.360376,0.142271,-58.763709,0.000000e+00,0.000000e+00,G011796
1,HVAEP2.G004481,593.302203,-2.924442,0.120817,-24.205573,1.943572e-129,1.570212e-125,G004481
2,HVAEP1.G000426,4327.267824,3.236053,0.133985,24.152419,7.042132e-129,3.792892e-125,G000426
3,HVAEP2.G004333,1218.077185,-2.766741,0.116381,-23.773192,6.326138e-125,2.555443e-121,G004333
4,HVAEP1.G000462,221.133476,3.253983,0.146209,22.255764,9.918827e-110,3.205368e-106,G000462

In [11]:
sample = "../results/network_analysis/genes_module_green.txt"
samplefile = "../results/network_analysis/goatools_ecokd1_sample_genes.txt"
sample_genes = []
with open(sample,"r") as sfile:
    with open(samplefile,"w") as sgenes:
        for line in sfile.readlines():
            gene = line.split(".")[1]
            gene = gene.rstrip()
            if gene in population_genes:
                if gene in df["gene"].to_list():
                    # print(gene)
                    sample_genes.append(gene)
                    sgenes.write(gene+"\n")

In [15]:
df[df["gene"].isin(sample_genes)].sort_values(by="log2FoldChange")

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,gene
1859,HVAEP2.G003470,858.672431,-1.121890,0.536688,-2.090394,0.036582,0.317795,G003470
2297,HVAEP15.G027980,109.557253,-0.515088,0.266212,-1.934882,0.053005,0.372694,G027980
1900,HVAEP15.G028548,12038.123576,-0.503625,0.242687,-2.075207,0.037967,0.322685,G028548
701,HVAEP15.G028734,4100.338559,-0.493957,0.165158,-2.990813,0.002782,0.063986,G028734
1481,HVAEP1.G002648,421.130139,-0.278075,0.122107,-2.277312,0.022768,0.248098,G002648
...,...,...,...,...,...,...,...,...
1532,HVAEP3.G006942,263.539558,0.276121,0.122933,2.246112,0.024697,0.260308,G006942
1242,HVAEP9.G015934,2096.347527,0.289584,0.119865,2.415922,0.015695,0.203837,G015934
1043,HVAEP5.G010088,383.471730,0.300746,0.117576,2.557896,0.010531,0.162985,G010088
502,HVAEP12.G023284,3136.244944,0.307990,0.090970,3.385632,0.000710,0.022812,G023284
1078,HVAEP1.G001789,303.408024,0.311828,0.123091,2.533305,0.011299,0.169206,G001789

In [12]:
outfile = "../results/network_analysis/enrichment_ecokd1_sample_genes.txt"

In [13]:
!find_enrichment.py $samplefile ../data/goatools_data/population.txt ../data/goatools_data/associations.txt --annofmt id2gos --alpha 0.05 --pval 0.05 --obo ../data/goatools_data/go-basic.obo --method fdr_bh --outfile $outfile --obsolete replace > /dev/null